/*
 * Copyright (C) 2005 Texas Instruments.
 *
 * (C) Copyright 2004
 * Jian Zhang, Texas Instruments, jzhang@ti.com.
 *
 * (C) Copyright 2002
 * Wolfgang Denk, DENX Software Engineering, wd@denx.de.
 *
 * (C) Copyright 2002
 * Sysgo Real-Time Solutions, GmbH <www.elinos.com>
 * Marius Groeger <mgroeger@sysgo.de>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#include <common.h>
#include <asm/arch/mem.h>
#include <version_autogenerated.h>
#include <timestamp_autogenerated.h>
#include <boot.h>

extern int misc_init_r (void);
extern u32 get_mem_type(void);

#ifdef CFG_PRINTF
int print_info(void)
{
#ifdef CFG_BOARD_NAME
	printf("\n\nTexas Instruments " X_LOADER_VERSION " for %s ("
		X_LOADER_DATE " " X_LOADER_TIME ")\n", CFG_BOARD_NAME);
#else
	printf("\n\nTexas Instruments " X_LOADER_VERSION " ("
		X_LOADER_DATE " " X_LOADER_TIME ")\n");
#endif
	return 0;
}
#endif

typedef int (init_fnc_t) (void);

init_fnc_t *init_sequence[] = {
	cpu_init,		/* basic cpu dependent setup */
	board_init,		/* basic board dependent setup */
	timer_init,
#ifdef CFG_PRINTF
 	serial_init,		/* serial communications setup */
	print_info,
#endif
  	nand_init,		/* board specific nand init */
  	NULL,
};

/*
 * Function to attempt reading a signed u-boot image from NAND
 *
 * At first read, if data starts with SIGNATURE, then next two words
 * hold destination address and length of data.
 */
#define SIGNGP_SIGNATURE (('S' << 24) | ('g' << 16) | ('n' << 8) | 'P')

int nand_read_signed_blocks(init_fnc_t **boot_fnc_ptr,
			unsigned long nand_start,
			unsigned long nand_end,
			unsigned int block_size, int *found)
{
	uchar *buf = (uchar *)CFG_LOADADDR;
	uchar *ram_addr;
	uchar *ram_start, *dest_addr;
	unsigned int nand_offset;
	unsigned int length;
	unsigned long *lbuf;
	int err = 0;

	*found = 0;
	/* Read first non-bad block and see if it has a signature */
	for (nand_offset = nand_start; nand_offset<nand_end; nand_offset+=block_size) {
		err = nand_read_block(buf, nand_offset);
		if (err < 0)
			return -1;
		if (err == 0)
			break;
	}

	if (err)
		return -1;	/* No usable block found */

	lbuf = (unsigned long *)buf;

#if 0
	printf("%s: signature %#lx length %#lx ram_start %#lx\n", __FUNCTION__, lbuf[0], lbuf[1], lbuf[2]);
#endif
	if (lbuf[0] != SIGNGP_SIGNATURE)
		return 0;

	/* Okay, have a signature; extract address; length */
	length = lbuf[1];
	ram_start = (uchar*)lbuf[2];

	/* Are they sane? */
#if defined(OMAP34XX_SIGNGP_DRAM_START) && defined(OMAP34XX_SIGNGP_DRAM_SIZE)
	if (((ram_start+3*sizeof(*lbuf)) < (uchar*)OMAP34XX_SIGNGP_DRAM_START)
		|| ((ram_start + length) > (uchar*)(OMAP34XX_SIGNGP_DRAM_START+OMAP34XX_SIGNGP_DRAM_SIZE))) {
		printf("Found 'SgnP' signature but start/length of 0x%#lx/0x%#lx not valid\n", __FUNCTION__, ram_start, length);
		return -2;
	}
#endif

	/* Backup dest_addr by sizeof signarture header */
	dest_addr = ram_start - 3*sizeof(*lbuf);

	/* Now re-read in the loop until we've read everything */
	nand_start = nand_offset;
	for (ram_addr = dest_addr/* , nand_offset = nand_start*/;
	     nand_offset < nand_end && (ram_addr < dest_addr + length);
	     nand_offset += block_size) {
#if 0
		printf("%s: read block offset %u to %p\n", __FUNCTION__, nand_offset, ram_addr);
#endif
		err = nand_read_block(ram_addr, nand_offset);
		if (err < 0)
			return -1;
		if (err > 0)
			continue;
		ram_addr += block_size;
	}
	printf("SgnP image: %#x bytes read from NAND at offset %#x to %p\n", length, nand_start, ram_start);
	*boot_fnc_ptr = (init_fnc_t *)ram_start;
	*found = 1;
	return 0;
}

void start_armboot (void)
{
  	init_fnc_t *boot_fnc_ptr = (init_fnc_t *)CFG_LOADADDR;
  	init_fnc_t **init_fnc_ptr;
	unsigned int size = 0;
 	int i;
	uchar *buf;
	int mem_type;
	int found;
	int err;
#ifdef CONFIG_DM3730LOGIC
	omap_boot_device_t boot_device;
	char *p;
#endif

   	for (init_fnc_ptr = init_sequence; *init_fnc_ptr; ++init_fnc_ptr) {
		if ((*init_fnc_ptr)() != 0) {
			hang ();
		}
	}

	misc_init_r();
	buf =  (uchar*) CFG_LOADADDR;

#ifdef CONFIG_DM3730LOGIC
	boot_device = omap_boot_device();
	if (boot_device == boot_device_sdmmc)
		p = "SDMMC";
	else if (boot_device == boot_device_nand)
		p = "NAND";
	else
		p = "Unknown!";
	printf("Boot: %s\n", p);
#endif

	//Splash screen
	lcd_init(boot_device);

#ifdef CONFIG_DM3730LOGIC
	/* If we booted from MMC, then look on MMC for the image.  Determine
	 * if booted from SDMMC by looking at VECT_HI from bootrom left in SRAM
	 * to see what device processor booted from */
	if (boot_device == boot_device_sdmmc) {
		size = mmc_boot(buf);
		if (size > 0) {
			buf += size;
			goto boot_it;
		}
	}
#endif

	mem_type = get_mem_type();

#ifdef ONENAND_START_BLOCK
	if (!size && mem_type == GPMC_ONENAND) {
		err = 0;
		for (i = ONENAND_START_BLOCK; !err && i < ONENAND_END_BLOCK; i++){
			err = onenand_read_block(buf+size, i);
				size += ONENAND_BLOCK_SIZE;
		}
		if (!err) {
			printf("%#lx bytes read from OneNAND to %p\n", size, (uchar*) CFG_LOADADDR);
			buf += size;
			goto boot_it;
		} else
			size = 0;
	}
#endif

	if (boot_device == boot_device_nand && !size && (mem_type == GPMC_NAND)) {
		err = nand_read_signed_blocks(&boot_fnc_ptr, NAND_UBOOT_START,
					NAND_UBOOT_END, NAND_BLOCK_SIZE, &found);
		if (!err && found)
			goto boot_it;

		for (i = NAND_UBOOT_START; !err && i < NAND_UBOOT_END; i+= NAND_BLOCK_SIZE){
			err = nand_read_block(buf+size, i);
			if (err > 0) {
				/* Skip the bad block */
				err = 0;
				continue;
			}
			size += NAND_BLOCK_SIZE;
		}
		if (!err) {
			printf("%#lx bytes read from nand at offset %#x to %p\n", size, NAND_UBOOT_START, (uchar*) CFG_LOADADDR);
			buf += size;
			goto boot_it;
		} else
			size = 0;
	}

#ifdef CONFIG_DM3730LOGIC
	/* if no u-boot in NAND, try the MMC(if we didn't already) */
	if ((size == 0) && (boot_device != boot_device_sdmmc)) {
		size = mmc_boot(buf);
		if (size > 0)
			buf += size;
	}
#endif

	if (size == 0) {
		printf("Can't find u-boot; wait for JTAG debugger...\n");
		hang();
	}

boot_it:
	
	/* go run Linux and never return */
	start_linux();
// 	((init_fnc_t *)boot_fnc_ptr)();

	/* should never come here */
	printf("Huh??? OS bootloader returned to X-loader!\n");
	hang();
}

void hang (void)
{
	/* call board specific hang function */
	board_hang();

	/* if board_hang() returns, hange here */
	printf("X-Loader hangs\n");
	for (;;);
}
